var a;
var b;
var c;
a = 10;
b = 'Sujata';
c = true;
console.log("a : " + a);
console.log("b : " + b);
console.log("c : " + c);
var x = 20;
// x='Girish';
var y = undefined;
console.log('typeof y ' + typeof y);
var z = null;
console.log('typeof z ' + typeof z);
